// Redux Action Types
export const AUTH_ACTIONS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
} as const;

export const BOOKING_ACTIONS = {
  FETCH_BOOKINGS_REQUEST: 'FETCH_BOOKINGS_REQUEST',
  FETCH_BOOKINGS_SUCCESS: 'FETCH_BOOKINGS_SUCCESS',
  FETCH_BOOKINGS_FAILURE: 'FETCH_BOOKINGS_FAILURE',
  CREATE_BOOKING_REQUEST: 'CREATE_BOOKING_REQUEST',
  CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
  CREATE_BOOKING_FAILURE: 'CREATE_BOOKING_FAILURE',
  CANCEL_BOOKING_REQUEST: 'CANCEL_BOOKING_REQUEST',
  CANCEL_BOOKING_SUCCESS: 'CANCEL_BOOKING_SUCCESS',
  CANCEL_BOOKING_FAILURE: 'CANCEL_BOOKING_FAILURE',
} as const;

export const COURSE_ACTIONS = {
  FETCH_COURSES_REQUEST: 'FETCH_COURSES_REQUEST',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAILURE: 'FETCH_COURSES_FAILURE',
  FETCH_COURSE_DETAILS_REQUEST: 'FETCH_COURSE_DETAILS_REQUEST',
  FETCH_COURSE_DETAILS_SUCCESS: 'FETCH_COURSE_DETAILS_SUCCESS',
  FETCH_COURSE_DETAILS_FAILURE: 'FETCH_COURSE_DETAILS_FAILURE',
} as const;

export const USER_ACTIONS = {
  FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
} as const; 